import { ArrowRight, BadgeCheck, BarChart3, Calculator, CheckCircle2, ChevronDown, ClipboardList, FileCheck2, Layers3, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";
import { Link } from "wouter";
import { ArrowLink, CheckList, SectionIntro } from "@/components/PageBlocks";

const services = [
  { icon: Calculator, title: "Construction Estimating", body: "Clear, trade-by-trade pricing built for real bid decisions." },
  { icon: Layers3, title: "Quantity Takeoffs", body: "Detailed quantities that help you buy accurately and reduce waste." },
  { icon: ClipboardList, title: "Material Takeoffs", body: "Organized material schedules ready for procurement and pricing." },
  { icon: BarChart3, title: "Cost Estimating", body: "Budget intelligence for planning, feasibility, and preconstruction." },
];
const trades = ["General & subcontractors", "Electrical & mechanical", "Plumbing & HVAC", "Roofing & waterproofing", "Concrete & earthwork", "Steel, demolition & utilities"];
const faqs = [{ q: "What drawings do you need to get started?", a: "Send the latest plan set, specifications, addenda, and any scope notes you have. We can work from PDFs, plan rooms, or shared folders." }, { q: "How quickly can you turn around an estimate?", a: "Most standard takeoffs are delivered in 2–5 business days. Rush delivery is available for active bid deadlines." }, { q: "Can you estimate specific trades?", a: "Yes. We support CSI divisions and specialty trades from concrete and earthwork through MEP, finishes, roofing, steel, and sitework." }];

export default function Home() {
  return <>
    <section className="relative overflow-hidden bg-[#111827] text-white"><div className="absolute inset-0 blueprint-grid opacity-70" /><div className="absolute -right-40 top-[-10rem] h-[38rem] w-[38rem] rounded-full bg-[#0047AB]/30 blur-3xl" /><div className="container relative grid min-h-[40rem] items-center gap-10 py-16 lg:grid-cols-[1.02fr_.98fr] lg:py-24"><div className="max-w-2xl"><div className="mb-6 flex items-center gap-3 text-[.7rem] font-bold uppercase tracking-[.2em] text-[#7FB2FF]"><span className="h-px w-8 bg-[#0066FF]" /> Construction estimating, done with intent</div><h1 className="display text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[5.45rem]">Win the right work with <span className="text-[#4A8BFF]">numbers you trust.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/68">Professional construction estimating, quantity takeoffs, and cost intelligence for contractors, builders, suppliers, and developers.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="btn-primary">Get a Free Quote <ArrowRight size={17} /></Link><Link href="/services" className="btn-ghost">Explore our services</Link></div><div className="mt-10 flex flex-wrap gap-x-7 gap-y-3 text-xs font-semibold text-white/55"><span className="flex items-center gap-2"><BadgeCheck size={15} className="text-[#4A8BFF]" /> Trade-specific expertise</span><span className="flex items-center gap-2"><BadgeCheck size={15} className="text-[#4A8BFF]" /> Bid-ready deliverables</span><span className="flex items-center gap-2"><BadgeCheck size={15} className="text-[#4A8BFF]" /> Responsive support</span></div></div><div className="relative hidden min-h-[27rem] lg:block"><div className="absolute right-0 top-0 h-[25rem] w-[86%] overflow-hidden border border-white/20 bg-[#203845] shadow-2xl"><img src="/manus-storage/construction-team_181951e1.webp" alt="Construction professionals reviewing plans on site" className="h-full w-full object-cover opacity-80 mix-blend-luminosity" /><div className="absolute inset-0 bg-gradient-to-tr from-[#111827]/80 via-transparent to-[#0066FF]/10" /></div><div className="absolute bottom-0 left-0 w-60 border border-white/20 bg-[#F3F4F6] p-5 text-[#0A0A0A] shadow-xl"><p className="eyebrow">Built for bids</p><p className="display mt-2 text-3xl font-semibold">Clear scope.<br />Clean quantities.</p><div className="mt-4 h-1 w-16 bg-[#0066FF]" /></div><div className="absolute right-[-1.2rem] top-[-1.2rem] flex h-20 w-20 items-center justify-center rounded-full border border-[#4A8BFF]/70 bg-[#0066FF] text-center text-[.65rem] font-bold uppercase leading-4 tracking-[.14em] text-white">Precision<br />first</div></div></div></section>
    <div className="border-b border-[#D1D5DB] bg-white"><div className="container grid gap-5 py-6 sm:grid-cols-3"><div className="flex items-center gap-3"><span className="display text-2xl font-bold text-[#0066FF]">01</span><p className="text-xs font-semibold leading-5 text-[#6B7280]">Detailed scope<br />coverage</p></div><div className="flex items-center gap-3"><span className="display text-2xl font-bold text-[#0066FF]">02</span><p className="text-xs font-semibold leading-5 text-[#6B7280]">Practical pricing<br />intelligence</p></div><div className="flex items-center gap-3"><span className="display text-2xl font-bold text-[#0066FF]">03</span><p className="text-xs font-semibold leading-5 text-[#6B7280]">Support when<br />deadlines move</p></div></div></div>
    <section className="section-pad bg-[#F3F4F6]"><div className="container"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionIntro eyebrow="What we do" title="Estimating that keeps projects moving." body="From early budgets to hard bids, we turn drawings into the information your team needs to make a confident next move." /><ArrowLink href="/services">View all services</ArrowLink></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{services.map(({ icon: Icon, title, body }, index) => <div key={title} className="card-lift border border-[#D1D5DB] bg-white p-6"><span className="flex h-11 w-11 items-center justify-center bg-[#E8F0FF] text-[#0047AB]"><Icon size={21} /></span><p className="mt-7 text-xs font-bold text-[#0066FF]">0{index + 1}</p><h3 className="display mt-2 text-xl font-semibold text-[#0A0A0A]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#6B7280]">{body}</p><Link href="/services" className="mt-6 inline-flex text-xs font-bold uppercase tracking-[.14em] text-[#0047AB] hover:text-[#0066FF]">Learn more <ArrowRight size={14} className="ml-2" /></Link></div>)}</div></div></section>
    <section className="section-pad bg-white"><div className="container grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative"><div className="absolute -left-5 -top-5 h-28 w-28 border-l border-t border-[#0066FF]" /><div className="h-[27rem] overflow-hidden bg-[#e8eff0]"><img src="/manus-storage/blueprint-plan_097c0ef9.webp" alt="Blueprint detail prepared for estimating" className="h-full w-full object-cover" /></div><div className="absolute bottom-[-1.6rem] right-[-1rem] bg-[#111827] px-6 py-5 text-white shadow-xl sm:right-[-2rem]"><p className="eyebrow text-[#7FB2FF]">The GES standard</p><p className="display mt-2 text-2xl font-semibold">Thorough by default.</p></div></div><div className="lg:pl-10"><SectionIntro eyebrow="Why teams choose us" title="A sharper view of cost, scope, and risk." body="Your estimate is more than a number. It is the foundation for buying, bidding, scheduling, and protecting margin." /><div className="mt-8 grid gap-5 sm:grid-cols-2"><CheckList items={["Line-item detail that is easy to review", "Trade-specific takeoff methodology", "Clear assumptions and exclusions", "Revision support when plans change"]} /></div><Link href="/about" className="btn-primary mt-9">Why Global Estimating <ArrowRight size={16} /></Link></div></div></section>
    <section className="section-pad bg-[#F3F4F6] blueprint-grid-light"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><SectionIntro eyebrow="Who we serve" title="Built around the way construction teams actually work." body="Whether you are pricing one scope or coordinating a full development pipeline, our process fits your project stage and your deadline." /><Link href="/industries" className="btn-ghost mt-8 border-[#0047AB] text-[#0047AB] hover:bg-[#E8F0FF]">Explore industries <ArrowRight size={16} /></Link></div><div className="grid gap-3 sm:grid-cols-2">{trades.map((trade, i) => <Link key={trade} href="/industries" className="group flex items-center justify-between border-b border-[#D1D5DB] py-4 text-sm font-semibold text-[#1F2937] hover:text-[#0066FF]"><span className="flex items-center gap-3"><span className="font-mono text-xs text-[#0066FF]">0{i + 1}</span>{trade}</span><ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
    <section className="section-pad bg-[#111827] text-white"><div className="container"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionIntro eyebrow="A simple, disciplined process" title="From plan set to bid-ready." body="No mystery handoffs. No black-box pricing. Just a clear workflow built around quality control." /><Link href="/how-it-works" className="btn-ghost shrink-0">See how it works <ArrowRight size={16} /></Link></div><div className="relative mt-14 grid gap-8 md:grid-cols-5 md:gap-3"><div className="absolute left-0 right-0 top-5 hidden h-px bg-white/15 md:block" />{["Submit project", "Review drawings", "Build takeoff", "Quality check", "Delivery"].map((step, i) => <div key={step} className="relative"><div className="flex items-center gap-4 md:block"><span className="relative z-10 flex h-10 w-10 items-center justify-center border border-[#4A8BFF] bg-[#111827] font-mono text-sm font-bold text-[#4A8BFF]">0{i + 1}</span><p className="mt-0 text-base font-semibold md:mt-6">{step}</p></div><p className="mt-2 max-w-[11rem] text-sm leading-6 text-white/50">{["Tell us what you need and when you need it.", "We review scope, plans, specs, and addenda.", "Quantities and costs are organized by trade.", "Every deliverable receives a thorough review.", "Receive clear, usable files for the next move."][i]}</p></div>)}</div></div></section>
    <section className="section-pad bg-white"><div className="container"><div className="grid gap-5 md:grid-cols-3"><div className="border-l-4 border-[#0066FF] bg-[#f6f8f8] p-7"><TrendingUp className="text-[#0066FF]" size={23} /><p className="display mt-6 text-3xl font-semibold text-[#0A0A0A]">Price with confidence</p><p className="mt-3 text-sm leading-6 text-[#6B7280]">See the scope clearly before you commit labor, materials, and time.</p></div><div className="border-l-4 border-[#0047AB] bg-[#f6f8f8] p-7"><Target className="text-[#0047AB]" size={23} /><p className="display mt-6 text-3xl font-semibold text-[#0A0A0A]">Protect your margin</p><p className="mt-3 text-sm leading-6 text-[#6B7280]">Know what is included, what is assumed, and where risk may sit.</p></div><div className="border-l-4 border-[#4A8BFF] bg-[#f6f8f8] p-7"><ShieldCheck className="text-[#4A8BFF]" size={23} /><p className="display mt-6 text-3xl font-semibold text-[#0A0A0A]">Move faster</p><p className="mt-3 text-sm leading-6 text-[#6B7280]">Reliable support that keeps your team focused on winning and building.</p></div></div></div></section>
    <section className="section-pad bg-[#F3F4F6]"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Client perspective</p><p className="display mt-4 text-4xl font-semibold leading-[1.08] text-[#0A0A0A]">“The numbers were clear, the scope was organized, and we knew exactly what we were bidding.”</p><div className="mt-8 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center bg-[#dcebec] font-bold text-[#0047AB]">JM</span><div><p className="text-sm font-bold text-[#0A0A0A]">Jordan M.</p><p className="text-xs text-[#6B7280]">Commercial General Contractor</p></div></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="border border-[#D1D5DB] bg-white p-7"><FileCheck2 className="text-[#0066FF]" /><p className="display mt-8 text-4xl font-semibold text-[#0A0A0A]">Bid-ready</p><p className="mt-2 text-sm leading-6 text-[#6B7280]">Schedules that make review and handoff simple.</p></div><div className="border border-[#D1D5DB] bg-white p-7"><Sparkles className="text-[#0047AB]" /><p className="display mt-8 text-4xl font-semibold text-[#0A0A0A]">Detail-first</p><p className="mt-2 text-sm leading-6 text-[#6B7280]">Assumptions, exclusions, and quantities you can stand behind.</p></div></div></div></section>
    <section className="section-pad bg-white"><div className="container"><SectionIntro eyebrow="Common questions" title="A better estimate starts with the right questions." body="Here are a few things clients ask before sending a project our way." /><div className="mt-10 max-w-3xl divide-y divide-[#D1D5DB] border-y border-[#D1D5DB]">{faqs.map(({ q, a }) => <details key={q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-base font-semibold text-[#1F2937]"><span>{q}</span><ChevronDown size={18} className="shrink-0 text-[#0066FF] transition-transform group-open:rotate-180" /></summary><p className="max-w-2xl pt-3 text-sm leading-6 text-[#6B7280]">{a}</p></details>)}</div><Link href="/faq" className="mt-8 inline-flex text-sm font-bold text-[#0047AB] hover:text-[#0066FF]">View all FAQs <ArrowRight size={16} className="ml-2" /></Link></div></section>
    <section className="bg-[#0066FF] text-white"><div className="container flex flex-col justify-between gap-8 py-12 md:flex-row md:items-center"><div><p className="eyebrow text-white/70">Have a project to price?</p><h2 className="display mt-2 text-3xl font-semibold sm:text-4xl">Let's turn your plans into a clear next move.</h2></div><Link href="/contact" className="btn-ghost shrink-0 border-white/60 hover:bg-white/10">Submit your project <ArrowRight size={17} /></Link></div></section>
  </>;
}
