import { ArrowRight, Building2, Factory, HardHat, Hospital, Landmark, Package, Pickaxe, Store, Truck, Users, Wrench } from "lucide-react";
import { Link } from "wouter";
import { Breadcrumb, PageHeader, SectionIntro } from "@/components/PageBlocks";

const categories = [{ icon: HardHat, eyebrow: "Contractors", title: "For teams on the tools", body: "Stay focused on delivery while we translate drawings into the quantities and costs your bids need.", items: ["General contractors", "Electrical contractors", "Mechanical contractors", "Plumbing contractors", "Roofing & waterproofing", "Painting, flooring & tile"] }, { icon: Package, eyebrow: "Suppliers", title: "For material partners", body: "Support your customers with accurate material quantities, scope clarity, and faster quote responses.", items: ["Flooring & tile suppliers", "Insulation suppliers", "Lumber suppliers", "Steel fabricators", "Specialty material vendors", "Distributor sales teams"] }, { icon: Building2, eyebrow: "Developers", title: "For the people planning ahead", body: "Make confident development and preconstruction decisions with budgets built for the next stage.", items: ["Commercial developers", "Healthcare developers", "Property developers", "Real estate investors", "Owners’ representatives", "Design-build teams"] }];
const icons = [Landmark, Hospital, Factory, Store, Pickaxe, Truck, Wrench, Users];
const trades = ["Commercial construction", "Healthcare & institutional", "Industrial & manufacturing", "Retail & tenant improvement", "Concrete & sitework", "Utilities & infrastructure", "MEP systems", "Renovation & adaptive reuse"];

export default function Industries() { return <><PageHeader eyebrow="Industries & trades" title="Built for the people who build." body="Our estimating services are designed around the decisions contractors, suppliers, developers, and investors make every day." /><Breadcrumb label="Industries & trades" /><section className="section-pad bg-white"><div className="container"><SectionIntro eyebrow="Who we serve" title="Practical support for every side of the project." body="Different roles need different visibility. We shape the deliverable around your scope, your audience, and your next decision." /><div className="mt-12 grid gap-5 lg:grid-cols-3">{categories.map(({ icon: Icon, eyebrow, title, body, items }) => <article key={title} className="border border-[#D1D5DB] bg-[#FFFFFF] p-7"><Icon className="text-[#0066FF]" size={25} /><p className="eyebrow mt-7">{eyebrow}</p><h2 className="display mt-3 text-2xl font-semibold text-[#0A0A0A]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#6B7280]">{body}</p><ul className="mt-6 space-y-3 border-t border-[#D1D5DB] pt-5">{items.map(item => <li key={item} className="flex items-center gap-2 text-sm font-semibold text-[#374151]"><span className="h-1.5 w-1.5 bg-[#0066FF]" />{item}</li>)}</ul></article>)}</div></div></section><section className="section-pad bg-[#F3F4F6] blueprint-grid-light"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Project environments</p><h2 className="display mt-3 text-4xl font-semibold text-[#0A0A0A]">Experience across the built environment.</h2><p className="mt-4 text-base leading-7 text-[#6B7280]">We bring a consistent estimating discipline to the project types where scope, schedule, and cost have to stay connected.</p><Link href="/contact" className="btn-primary mt-8">Discuss your project <ArrowRight size={16} /></Link></div><div className="grid gap-x-6 gap-y-3 sm:grid-cols-2">{trades.map((trade, i) => { const Icon = icons[i]; return <div key={trade} className="flex items-center gap-4 border-b border-[#D1D5DB] py-5"><span className="flex h-10 w-10 items-center justify-center bg-white text-[#0047AB]"><Icon size={19} /></span><div><p className="font-mono text-[.65rem] text-[#0066FF]">SCOPE {String(i + 1).padStart(2, "0")}</p><p className="mt-1 text-sm font-bold text-[#1F2937]">{trade}</p></div></div> })}</div></div></section><section className="section-pad bg-[#111827] text-white"><div className="container flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow text-[#7FB2FF]">Your scope is our starting point</p><h2 className="display mt-3 max-w-2xl text-4xl font-semibold">Tell us what you are building. We will tell you what we can see.</h2></div><Link href="/contact" className="btn-primary shrink-0">Get a free quote <ArrowRight size={16} /></Link></div></section></>; }
