import { AlertCircle, CheckCircle2, FileUp, Loader2, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { trpc } from "@/lib/trpc";

const initial = { name: "", company: "", email: "", phone: "", projectType: "", projectLocation: "", requiredService: "", projectDetails: "", deadline: "" };

export default function QuoteForm() {
  const [form, setForm] = useState(initial);
  const [file, setFile] = useState<File | null>(null);
  const [formError, setFormError] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const submit = trpc.quote.submit.useMutation({ onSuccess: () => { setSubmitted(true); setForm(initial); setFile(null); }, onError: (error) => setFormError(error.message || "Something went wrong. Please try again.") });
  const update = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const handleSubmit = async (event: FormEvent) => {
    event.preventDefault(); setFormError(""); setSubmitted(false);
    if (!form.name || !form.email || !form.projectType || !form.requiredService || !form.projectDetails) { setFormError("Please complete the required fields so we can review your project."); return; }
    if (file && file.size > 8 * 1024 * 1024) { setFormError("Please choose a file smaller than 8 MB."); return; }
    let attachmentData: string | undefined;
    if (file) attachmentData = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
    submit.mutate({ ...form, attachmentName: file?.name, attachmentType: file?.type, attachmentData });
  };
  const field = (key: keyof typeof initial, label: string, placeholder: string, required = false) => <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-[#6B7280]">{label}{required && <span className="text-[#0066FF]"> *</span>}</span><input required={required} value={form[key]} onChange={(e) => update(key, e.target.value)} placeholder={placeholder} className="input-base" /></label>;
  if (submitted) return <div className="border border-[#A7F3D0] bg-[#f1faf4] p-8"><CheckCircle2 className="text-[#047857]" size={28} /><h3 className="display mt-5 text-3xl font-semibold text-[#064E3B]">Project received.</h3><p className="mt-3 text-sm leading-6 text-[#047857]">Thanks for reaching out. Our team will review the details and follow up with timing and next steps.</p><button onClick={() => setSubmitted(false)} className="mt-6 text-sm font-bold text-[#0047AB] hover:text-[#0066FF]">Submit another project</button></div>;
  return <form onSubmit={handleSubmit} className="space-y-5" noValidate><div className="grid gap-5 sm:grid-cols-2">{field("name", "Your name", "Jane Smith", true)}{field("company", "Company", "Company name")}{field("email", "Email", "jane@company.com", true)}{field("phone", "Phone / WhatsApp", "+1 (555) 000-0000")}{field("projectType", "Project type", "Commercial, residential, industrial…", true)}{field("projectLocation", "Project location", "City, state / country")}</div><div className="grid gap-5 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-[#6B7280]">Required service <span className="text-[#0066FF]">*</span></span><select required value={form.requiredService} onChange={(e) => update("requiredService", e.target.value)} className="input-base"><option value="">Select a service</option><option>Construction estimating</option><option>Quantity takeoff</option><option>Material takeoff</option><option>Cost estimating</option><option>Bid preparation support</option><option>Trade-specific estimating</option></select></label>{field("deadline", "Project deadline", "When do you need the estimate?")}</div><label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.12em] text-[#6B7280]">Project details <span className="text-[#0066FF]">*</span></span><textarea required value={form.projectDetails} onChange={(e) => update("projectDetails", e.target.value)} placeholder="Tell us about the scope, trades, plan set, and anything else we should know." rows={5} className="input-base resize-y" /></label><label className="flex cursor-pointer items-center gap-3 border border-dashed border-[#b9c9cd] bg-[#FFFFFF] p-4 hover:border-[#0066FF]"><FileUp className="shrink-0 text-[#0047AB]" size={20} /><span className="min-w-0 flex-1"><span className="block text-sm font-bold text-[#1F2937]">{file ? file.name : "Upload drawings or plans"}</span><span className="mt-1 block text-xs text-[#6B7280]">PDF, XLSX, DWG, or ZIP · max 8 MB</span></span><input type="file" accept=".pdf,.xlsx,.xls,.dwg,.zip,.png,.jpg,.jpeg" className="sr-only" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>{formError && <div className="flex items-start gap-2 bg-[#fff3f0] p-3 text-sm text-[#991B1B]"><AlertCircle className="mt-0.5 shrink-0" size={16} />{formError}</div>}<button type="submit" disabled={submit.isPending} className="btn-primary w-full sm:w-auto">{submit.isPending ? <><Loader2 className="animate-spin" size={16} /> Sending project…</> : <><Send size={16} /> Submit your project</>}</button><p className="text-xs leading-5 text-[#6B7280]">By submitting, you agree to be contacted about this project. We use your details only to respond to your request.</p></form>;
}
